WardrobeApp/Models/Outfit.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outfit
    {
        public int OutfitsID { get; set; }
        public string Name { get; set; }
        public string Occasion { get; set; }
        public string Season { get; set; }
        public int TopsID { get; set; }
        public int BottomsID { get; set; }
        public int ShoesID { get; set; }
        public int AccessoriesID { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Bottom Bottom { get; set; }
        public virtual Sho Sho { get; set; }
        public virtual Top Top { get; set; }
    }
}

WardrobeApp/Controllers/AccessoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WardrobeApp.Models;

namespace WardrobeApp.Controllers
{
    public class AccessoriesController : Controller
    {
        private WardrobeMVCEntities db = new WardrobeMVCEntities();

        // GET: Accessories
        public ActionResult Index()
        {
            return View(db.Accessories.ToList());
        }

        // GET: Accessories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Accessory accessory = db.Accessories.Find(id);
            if (accessory == null)
            {
                return HttpNotFound();
            }
            return View(accessory);
        }

        // GET: Accessories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Accessories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AccessoriesID,Name,Photo,Color,Occasion,Type,Season")] Accessory accessory)
        {
            if (ModelState.IsValid)
            {
                db.Accessories.Add(accessory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(accessory);
        }

        // GET: Accessories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Accessory accessory = db.Accessories.Find(id);
            if (accessory == null)
            {
                return HttpNotFound();
            }
            return View(accessory);
        }

        // POST: Accessories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AccessoriesID,Name,Photo,Color,Occasion,Type,Season")] Accessory accessory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(accessory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(accessory);
        }

        // GET: Accessories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Accessory accessory = db.Accessories.Find(id);
            if (accessory == null)
            {
                return HttpNotFound();
            }
            return View(accessory);
        }

        // POST: Accessories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Accessory accessory = db.Accessories.Find(id);
            db.Accessories.Remove(accessory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WardrobeApp/Controllers/BottomsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WardrobeApp.Models;

namespace WardrobeApp.Controllers
{
    public class BottomsController : Controller
    {
        private WardrobeMVCEntities db = new WardrobeMVCEntities();

        // GET: Bottoms
        public ActionResult Index()
        {
            return View(db.Bottoms.ToList());
        }

        // GET: Bottoms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bottom bottom = db.Bottoms.Find(id);
            if (bottom == null)
            {
                return HttpNotFound();
            }
            return View(bottom);
        }

        // GET: Bottoms/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bottoms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BottomsID,Name,Photo,Color,Occasion,Type,Season")] Bottom bottom)
        {
            if (ModelState.IsValid)
            {
                db.Bottoms.Add(bottom);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bottom);
        }

        // GET: Bottoms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bottom bottom = db.Bottoms.Find(id);
            if (bottom == null)
            {
                return HttpNotFound();
            }
            return View(bottom);
        }

        // POST: Bottoms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BottomsID,Name,Photo,Color,Occasion,Type,Season")] Bottom bottom)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bottom).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bottom);
        }

        // GET: Bottoms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bottom bottom = db.Bottoms.Find(id);
            if (bottom == null)
            {
                return HttpNotFound();
            }
            return View(bottom);
        }

        // POST: Bottoms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bottom bottom = db.Bottoms.Find(id);
            db.Bottoms.Remove(bottom);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WardrobeApp/Controllers/OutfitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WardrobeApp.Models;

namespace WardrobeApp.Controllers
{
    public class OutfitsController : Controller
    {
        private WardrobeMVCEntities db = new WardrobeMVCEntities();

        // GET: Outfits
        public ActionResult Index()
        {
            var outfits = db.Outfits.Include(o => o.Accessory).Include(o => o.Bottom).Include(o => o.Sho).Include(o => o.Top);
            return View(outfits.ToList());
        }

        // GET: Outfits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Outfit outfit = db.Outfits.Find(id);
            if (outfit == null)
            {
                return HttpNotFound();
            }
            return View(outfit);
        }

        // GET: Outfits/Create
        public ActionResult Create()
        {
            ViewBag.AccessoriesID = new SelectList(db.Accessories, "AccessoriesID", "Name");
            ViewBag.BottomsID = new SelectList(db.Bottoms, "BottomsID", "Name");
            ViewBag.ShoesID = new SelectList(db.Shoes, "ShoesID", "Name");
            ViewBag.TopsID = new SelectList(db.Tops, "TopsID", "Name");
            return View();
        }

        // POST: Outfits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OutfitsID,Name,Occasion,Season,TopsID,BottomsID,ShoesID,AccessoriesID")] Outfit outfit)
        {
            if (ModelState.IsValid)
            {
                db.Outfits.Add(outfit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AccessoriesID = new SelectList(db.Accessories, "AccessoriesID", "Name", outfit.AccessoriesID);
            ViewBag.BottomsID = new SelectList(db.Bottoms, "BottomsID", "Name", outfit.BottomsID);
            ViewBag.ShoesID = new SelectList(db.Shoes, "ShoesID", "Name", outfit.ShoesID);
            ViewBag.TopsID = new SelectList(db.Tops, "TopsID", "Name", outfit.TopsID);
            return View(outfit);
        }

        // GET: Outfits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Outfit outfit = db.Outfits.Find(id);
            if (outfit == null)
            {
                return HttpNotFound();
            }
            ViewBag.AccessoriesID = new SelectList(db.Accessories, "AccessoriesID", "Name", outfit.AccessoriesID);
            ViewBag.BottomsID = new SelectList(db.Bottoms, "BottomsID", "Name", outfit.BottomsID);
            ViewBag.ShoesID = new SelectList(db.Shoes, "ShoesID", "Name", outfit.ShoesID);
            ViewBag.TopsID = new SelectList(db.Tops, "TopsID", "Name", outfit.TopsID);
            return View(outfit);
        }

        // POST: Outfits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OutfitsID,Name,Occasion,Season,TopsID,BottomsID,ShoesID,AccessoriesID")] Outfit outfit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(outfit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AccessoriesID = new SelectList(db.Accessories, "AccessoriesID", "Name", outfit.AccessoriesID);
            ViewBag.BottomsID = new SelectList(db.Bottoms, "BottomsID", "Name", outfit.BottomsID);
            ViewBag.ShoesID = new SelectList(db.Shoes, "ShoesID", "Name", outfit.ShoesID);
            ViewBag.TopsID = new SelectList(db.Tops, "TopsID", "Name", outfit.TopsID);
            return View(outfit);
        }

        // GET: Outfits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Outfit outfit = db.Outfits.Find(id);
            if (outfit == null)
            {
                return HttpNotFound();
            }
            return View(outfit);
        }

        // POST: Outfits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Outfit outfit = db.Outfits.Find(id);
            db.Outfits.Remove(outfit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WardrobeApp/Controllers/TopsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WardrobeApp.Models;

namespace WardrobeApp.Controllers
{
    public class TopsController : Controller
    {
        private WardrobeMVCEntities db = new WardrobeMVCEntities();

        // GET: Tops
        public ActionResult Index()
        {
            return View(db.Tops.ToList());
        }

        // GET: Tops/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Top top = db.Tops.Find(id);
            if (top == null)
            {
                return HttpNotFound();
            }
            return View(top);
        }

        // GET: Tops/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TopsID,Name,Photo,Color,Occasion,Type,Season")] Top top)
        {
            if (ModelState.IsValid)
            {
                db.Tops.Add(top);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(top);
        }

        // GET: Tops/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Top top = db.Tops.Find(id);
            if (top == null)
            {
                return HttpNotFound();
            }
            return View(top);
        }

        // POST: Tops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TopsID,Name,Photo,Color,Occasion,Type,Season")] Top top)
        {
            if (ModelState.IsValid)
            {
                db.Entry(top).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(top);
        }

        // GET: Tops/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Top top = db.Tops.Find(id);
            if (top == null)
            {
                return HttpNotFound();
            }
            return View(top);
        }

        // POST: Tops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Top top = db.Tops.Find(id);
            db.Tops.Remove(top);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WardrobeApp/Views/Outfits/Create.cshtml
@model WardrobeApp.Models.Outfit

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="row details">
    <div class="form-horizontal">
        <h4>Create an Outfit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occasion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occasion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occasion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Season, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Season, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Season, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TopsID, "Top", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TopsID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TopsID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BottomsID, "Bottom", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BottomsID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BottomsID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShoesID, "Shoes", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShoesID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShoesID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccessoriesID, "Accessory", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AccessoriesID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AccessoriesID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4">
                <input type="submit" value="Create" class="btn btn-default" />
                <a href="/Outfits/Index" class="btn btn-default">Return to List</a>
            </div>
        </div>
    </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WardrobeApp/Views/Outfits/Delete.cshtml
@model WardrobeApp.Models.Outfit

@{
    ViewBag.Title = "Delete";
}

<div class="col-md-12 delete">
    <i class="fas fa-exclamation-triangle"></i>
    <h3>Are you sure you want to delete this outfit?</h3>
</div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            <a href="/Outfits/Index" class="btn btn-default">Return to List</a>
        </div>
    }
</div>

WardrobeApp/Views/Outfits/Details.cshtml
@model WardrobeApp.Models.Outfit

@{
    ViewBag.Title = "Details";
}

<div class="row details">
    <div class="col-md-1"></div>
    <div class="col-md-6">
        <section class="gallery">
            <article id="one" class="target">
                <figure>
                    <img src="@Html.DisplayFor(model => model.Top.Photo)" alt="Top Photo" class="outfits-gallery">
                </figure>
            </article>
            <article id="two" class="target">
                <figure>
                    <img src="@Html.DisplayFor(model => model.Bottom.Photo)" alt="Bottom Photo" class="outfits-gallery">
                </figure>
            </article>
            <article id="three" class="target">
                <figure>
                    <img src="@Html.DisplayFor(model => model.Accessory.Photo)" alt="Accessory Photo" class="outfits-gallery">
                </figure>
            </article>
            <article id="four" class="target">
                <figure>
                    <img src="@Html.DisplayFor(model => model.Sho.Photo)" alt="Shoes Photo" class="outfits-gallery">
                </figure>
            </article>
        </section>
    </div>

    <div class="col-md-4 well-details">
        <h5>@Html.DisplayFor(model => model.Name)</h5>
        <div class="panel">
            <p>
                <u>Occasion</u>: @Html.DisplayFor(model => model.Occasion)<br />
                <u>Season</u>: @Html.DisplayFor(model => model.Season)<br /><br />

                <nav>
                    <ul>
                        <li><a href="#one">@Html.DisplayFor(model => model.Top.Name)</a></li><br />
                        <li><a href="#two">@Html.DisplayFor(model => model.Bottom.Name)</a></li><br />
                        <li><a href="#three">@Html.DisplayFor(model => model.Accessory.Name)</a></li><br />
                        <li><a href="#four">@Html.DisplayFor(model => model.Sho.Name)</a></li><br />
                    </ul>
                </nav>
            </p><br /><br />
            <p>
                <button type="button" class="btn btn-default">Edit<a href="@Url.Action("Edit", new { id = Model.OutfitsID })"> <i class="far fa-edit"></i></a></button>
                <button type="button" class="btn btn-default">Return to List of Outfits<a href="/Outfits/Index"> <i class="fas fa-list-ul"></i></a></button>
            </p>

        </div>


    </div>

    <div class="col-md-1"></div>
</div></div>

@*<h2>Details</h2>

<div>
    <h4>Outfit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Occasion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Occasion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Season)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Season)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Accessory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Accessory.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bottom.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bottom.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sho.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sho.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Top.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Top.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OutfitsID }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

WardrobeApp/Views/Outfits/Index.cshtml
@model IEnumerable<WardrobeApp.Models.Outfit>

@{
    ViewBag.Title = "Index";
}

<h4>Outfits</h4>

<p>
    <button type="button" class="btn btn-default">Put Together a New Outfit<a href="/Outfits/Create"> <i class="fas fa-plus-circle"></i></a></button>
</p>


@foreach (var item in Model)
{

    <div class="col-md-4">
        <div class="thumbnail outfit">
            <div class="caption outfit">
                <h3>@Html.DisplayFor(modelItem => item.Name)</h3>
                <img src="@Html.DisplayFor(modelItem => item.Top.Photo)" class="outfit-thumbs" />
                <img src="@Html.DisplayFor(modelItem => item.Bottom.Photo)" class="outfit-thumbs" />
                <img src="@Html.DisplayFor(modelItem => item.Accessory.Photo)" class="outfit-thumbs" />
                <img src="@Html.DisplayFor(modelItem => item.Sho.Photo)" class="outfit-thumbs" /><br /><br />
                <p>
                    <button type="button" class="btn btn-default"><a href="@Url.Action("Details", "Tops", new { id = item.TopsID })">@Html.DisplayFor(modelItem => item.Top.Name)</a></button>
                    <button type="button" class="btn btn-default"><a href="@Url.Action("Details", "Bottoms", new { id = item.BottomsID })">@Html.DisplayFor(modelItem => item.Bottom.Name)</a></button>
                    <button type="button" class="btn btn-default"><a href="@Url.Action("Details", "Accessories", new { id = item.AccessoriesID })">@Html.DisplayFor(modelItem => item.Accessory.Name)</a></button>
                    <button type="button" class="btn btn-default"><a href="@Url.Action("Details", "Shoes", new { id = item.ShoesID })">@Html.DisplayFor(modelItem => item.Sho.Name)</a></button>
                </p>
                <p>
                    <a href="@Url.Action("Edit", "Outfits", new { id = item.OutfitsID })" class="fas fa-edit"></a>
                    <a href="@Url.Action("Details", "Outfits", new { id = item.OutfitsID })" class="fas fa-info-circle"></a>
                    <a href="@Url.Action("Delete", "Outfits", new { id = item.OutfitsID})" class="fas fa-trash-alt"></a>
                </p>

            </div>
        </div>
    </div>

}
</div>