WardrobeApp/Controllers/ShoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WardrobeApp.Models;

namespace WardrobeApp.Controllers
{
    public class ShoesController : Controller
    {
        private WardrobeMVCEntities db = new WardrobeMVCEntities();

        // GET: Shoes
        public ActionResult Index()
        {
            return View(db.Shoes.ToList());
        }

        // GET: Shoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sho sho = db.Shoes.Find(id);
            if (sho == null)
            {
                return HttpNotFound();
            }
            return View(sho);
        }

        // GET: Shoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Shoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ShoesID,Name,Photo,Color,Occasion,Type,Season")] Sho sho)
        {
            if (ModelState.IsValid)
            {
                db.Shoes.Add(sho);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sho);
        }

        // GET: Shoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sho sho = db.Shoes.Find(id);
            if (sho == null)
            {
                return HttpNotFound();
            }
            return View(sho);
        }

        // POST: Shoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ShoesID,Name,Photo,Color,Occasion,Type,Season")] Sho sho)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sho).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sho);
        }

        // GET: Shoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sho sho = db.Shoes.Find(id);
            if (sho == null)
            {
                return HttpNotFound();
            }
            return View(sho);
        }

        // POST: Shoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sho sho = db.Shoes.Find(id);
            db.Shoes.Remove(sho);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WardrobeApp/Views/Shoes/Create.cshtml
@model WardrobeApp.Models.Sho

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
<div class="row details">
    <div class="form-horizontal">
        <h4>Add Shoes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occasion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occasion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occasion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Season, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Season, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Season, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4">
                <input type="submit" value="Create" class="btn btn-default" />
                <a href="/Shoes/Index" class="btn btn-default">Return to List</a>
            </div>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WardrobeApp/Views/Shoes/Delete.cshtml
@model WardrobeApp.Models.Sho

@{
    ViewBag.Title = "Delete";
}

<div class="col-md-12 delete">
    <i class="fas fa-exclamation-triangle"></i>
    <h3>Are you sure you want to delete this item?</h3>
</div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            <a href="/Shoes/Index" class="btn btn-default">Return to List</a>
        </div>
    }
</div>

WardrobeApp/Views/Shoes/Details.cshtml
@model WardrobeApp.Models.Sho

@{
    ViewBag.Title = "Details";
}

<div class="row details">
    <div class="col-md-1"></div>
    <div class="col-md-4">
        <div class="thumbnail details-thumb">
            <img src="@Html.DisplayFor(model => model.Photo)" class="clothing-details" />
        </div>
    </div>

    <div class="col-md-6 well-details">
        <h5>@Html.DisplayFor(model => model.Name)</h5>
        <div class='banner'><div class='banner_l'></div><div class='banner_txt'>@Html.DisplayFor(model => model.Type)</div><div class='banner_r'></div></div>
        <div class="panel">
            <p>
                <u>Color</u>: @Html.DisplayFor(model => model.Color)<br />
                <u>Occasion</u>: @Html.DisplayFor(model => model.Occasion)<br />
                <u>Season</u>: @Html.DisplayFor(model => model.Season)
            </p><br /><br />
            <p>
                <button type="button" class="btn btn-default">Edit<a href="@Url.Action("Edit", new { id = Model.ShoesID })"> <i class="far fa-edit"></i></a></button>
                <button type="button" class="btn btn-default">Return to List of Shoes<a href="/Shoes/Index"> <i class="fas fa-list-ul"></i></a></button>
            </p>

        </div>


    </div>

    <div class="col-md-1"></div>
</div></div>

WardrobeApp/Views/Shoes/Edit.cshtml
@model WardrobeApp.Models.Sho

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row details">
    <div class="form-horizontal">
        <h4>Edit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ShoesID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occasion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occasion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occasion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Season, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Season, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Season, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4">
                <input type="submit" value="Save" class="btn btn-default" />
                <a href="/Shoes/Index" class="btn btn-default">Return to List</a>
            </div>
        </div>
    </div>
        </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WardrobeApp/Views/Shoes/Index.cshtml
@model IEnumerable<WardrobeApp.Models.Sho>

@{
    ViewBag.Title = "Index";
}

<h4>Shoes</h4>

<p>
    <button type="button" class="btn btn-default">Add New Shoes to the Closet<a href="/Shoes/Create"> <i class="fas fa-plus-circle"></i></a></button>
</p>

@foreach (var item in Model)
{
    <div class="col-md-4">
        <div class="thumbnail outfit">
            <div class="caption outfit">
                <h3>@Html.DisplayFor(modelItem => item.Name)</h3>
                <img src="@Html.DisplayFor(modelItem => item.Photo)" class="clothes-thumbnail" /><br /><br />
                <p>
                    <div class='banner'><div class='banner_l'></div><div class='banner_txt'>@Html.DisplayFor(modelItem => item.Type)</div><div class='banner_r'></div></div>
                </p>
                <p>
                    <a href="@Url.Action("Edit", "Shoes", new { id = item.ShoesID })" class="fas fa-edit"></a>
                    <a href="@Url.Action("Details", "Shoes", new { id = item.ShoesID })" class="fas fa-info-circle"></a>
                    <a href="@Url.Action("Delete", "Shoes", new { id = item.ShoesID})" class="fas fa-trash-alt"></a>
                </p>

            </div>
        </div>
    </div>
}

</div>